name: CI
on:
  pull_request: {}
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Setup DB
        run: bundle exec rake db:setup
      - name: Run Tests
        run: bundle exec rake
  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [test]
    steps:
      - name: Dispatch Release
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Generate New Release
          token: ${{ secrets.GITHUB_TOKEN }}
